-- Presupuestos de eventos de empresa: sustituye el Excel "DESGLOSE EVENTO"
-- + el Word/PDF que se envía al cliente.
--
--  * quote_catalog: tarifas por defecto (pistas, bolas, gestión del torneo,
--    monitores, ludoteca...) con el texto que aparece en el PDF del cliente.
--    Se editan desde la propia app (Presupuestos > Tarifas).
--  * event_quotes: cada presupuesto, con su desglose interno (lines) y la
--    lista de servicios que ve el cliente (services). Al aceptarlo se puede
--    pasar al calendario de Eventos (event_id).

create table if not exists quote_catalog (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  category text not null check (category in ('pistas','material','personal','actividades','catering','premios','otros')),
  name text not null,
  -- 'pista_hora' = nº pistas x horas x precio; 'hora' = cantidad x horas x
  -- precio (ej. monitores); 'unidad' = cantidad x precio; 'persona' =
  -- participantes x precio; 'fijo' = importe cerrado.
  unit text not null check (unit in ('pista_hora','hora','unidad','persona','fijo')),
  default_price numeric(10,2) not null default 0,
  -- Cantidad automática: 'pistas' (= nº de pistas de pádel del presupuesto,
  -- como los botes de bolas) o 'participantes'. null = manual.
  qty_rule text check (qty_rule in ('pistas','participantes')),
  -- Texto para el PDF del cliente. Una línea por viñeta. Admite {n}
  -- (cantidad), {participantes}, {horas}, {descripcion}. Vacío = no sale.
  client_text text not null default '',
  sort int not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists event_quotes (
  id uuid primary key default gen_random_uuid(),
  seq bigint generated by default as identity,
  club_id uuid references clubs(id) on delete set null,
  title text not null,
  company text not null,
  contact_name text,
  contact_email text,
  contact_phone text,
  event_date date,
  date_label text,            -- texto libre que sale en el PDF ("Sábado 7 noviembre 2026", "17 o 24 de abril")
  participants int,
  lines jsonb not null default '[]',     -- desglose interno (no lo ve el cliente)
  services jsonb not null default '[]',  -- viñetas del PDF
  services_custom boolean not null default false, -- true = viñetas editadas a mano, no regenerar
  prizes_text text,
  discount_pct numeric(5,2) not null default 0,
  total_override numeric(10,2),          -- precio cerrado distinto al calculado
  total numeric(10,2) not null default 0,
  vat_mode text not null default 'exento' check (vat_mode in ('exento','mas_iva','iva_incluido','ninguno')),
  client_logo text,                      -- data URL (PNG reducido) para no depender de CORS al generar el PDF
  status text not null default 'borrador' check (status in ('borrador','enviado','aceptado','rechazado')),
  event_id uuid references events(id) on delete set null,
  notes text,                            -- notas internas
  sent_at timestamptz,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists event_quotes_event_date_idx on event_quotes (event_date);
create index if not exists event_quotes_status_idx on event_quotes (status);

alter table quote_catalog enable row level security;
create policy quote_catalog_select on quote_catalog for select using (auth.uid() is not null);
create policy quote_catalog_write on quote_catalog for all
  using (current_role_name() in ('admin','coordinacion','direccion'))
  with check (current_role_name() in ('admin','coordinacion','direccion'));

alter table event_quotes enable row level security;
create policy event_quotes_select on event_quotes for select
  using (current_role_name() in ('admin','coordinacion','direccion','administracion','front_desk'));
create policy event_quotes_write on event_quotes for all
  using (current_role_name() in ('admin','coordinacion','direccion','administracion','front_desk'))
  with check (current_role_name() in ('admin','coordinacion','direccion','administracion','front_desk'));

-- Tarifas iniciales sacadas de los presupuestos 2025-2026 del Excel.
insert into quote_catalog (key, category, name, unit, default_price, qty_rule, client_text, sort) values
  ('pista_padel_indoor', 'pistas', 'Pista de pádel indoor', 'pista_hora', 20, null,
   'Reserva de {n} pistas de pádel indoor para el desarrollo del evento.', 10),
  ('pista_padel_outdoor', 'pistas', 'Pista de pádel outdoor', 'pista_hora', 10, null,
   'Reserva de {n} pistas de pádel outdoor para el desarrollo del evento.', 11),
  ('campo_futbol7', 'pistas', 'Campo de fútbol 7', 'pista_hora', 90, null,
   'Reserva de {n} campo de fútbol 7 para el desarrollo del evento.', 12),
  ('botes_bolas', 'material', 'Botes de bolas', 'unidad', 7, 'pistas',
   'Bolas premium para el evento', 20),
  ('alquiler_palas', 'material', 'Alquiler de palas', 'unidad', 5, null,
   'Alquiler de {n} palas de pádel', 21),
  ('gestion_integral', 'personal', 'Gestión integral del torneo', 'fijo', 400, null,
   E'Organización de un torneo de pádel para {participantes} jugadores.\nTV con publicidad, roll ups, ... durante el desarrollo del evento.\nMesa de control (mesas y sillas) para la gestión del evento\nGestión deportiva del evento dirigido por juez árbitro\nGestión de cuadros y enfrentamientos\nPersonal de apoyo en recepción durante el evento.\nServicio de taquillas', 30),
  ('gestion_evento', 'personal', 'Gestión del evento', 'fijo', 300, null,
   E'Coordinación y gestión del evento por parte del club\nPersonal de apoyo en recepción durante el evento.', 31),
  ('entrenador_hora', 'personal', 'Entrenador/monitor (hora)', 'hora', 50, null,
   'Clases dirigidas por {n} entrenadores titulados ({horas} h)', 32),
  ('juez_arbitro_dia', 'personal', 'Juez árbitro (día)', 'unidad', 120, null,
   'Juez árbitro durante el evento', 33),
  ('personal_apoyo', 'personal', 'Personal de apoyo', 'fijo', 200, null,
   'Personal de apoyo durante el evento.', 34),
  ('clase_aadd', 'actividades', 'Actividad dirigida (hora)', 'hora', 75, null,
   'Actividades dirigidas con monitor ({horas} h)', 40),
  ('ludoteca', 'actividades', 'Ludoteca (hora)', 'hora', 50, null,
   'Servicio de ludoteca para los más pequeños', 41),
  ('castillo_hinchable', 'actividades', 'Castillo hinchable (hora)', 'hora', 150, null,
   'Castillo hinchable', 42),
  ('sala_profe', 'actividades', 'Sala + profesor (Zumba, Pilates...)', 'unidad', 100, null,
   'Sesión de {descripcion} con profesor', 43),
  ('sala', 'actividades', 'Sala (Yoga, Spinning...)', 'unidad', 50, null,
   'Sala de {descripcion}', 44),
  ('dj', 'actividades', 'DJ', 'fijo', 0, null, 'DJ durante el evento', 45),
  ('avituallamiento', 'catering', 'Avituallamiento (agua + fruta) por persona', 'persona', 3, 'participantes',
   'Avituallamiento para los participantes (agua y fruta)', 50),
  ('botella_agua', 'catering', 'Botella de agua', 'unidad', 2, null,
   '{n} botellas de agua', 51),
  ('consumicion', 'catering', 'Consumición', 'unidad', 4, null,
   'Consumiciones en cafetería', 52),
  ('welcome_pack', 'catering', 'Welcome pack', 'unidad', 0, 'participantes',
   'Welcome pack para los participantes', 53),
  ('trofeo', 'premios', 'Trofeo / medalla', 'unidad', 15, null,
   'Trofeos para los ganadores', 60),
  ('cupon_premio', 'premios', 'Cupón regalo (premio)', 'unidad', 80, null,
   '{descripcion}', 61),
  ('alquiler_espacio', 'otros', 'Alquiler de espacio', 'fijo', 90, null,
   'Alquiler de espacio para {descripcion}', 70),
  ('montaje_lonas', 'otros', 'Montaje de lonas / carpas', 'fijo', 125, null,
   'Montaje de lonas publicitarias', 71),
  ('vestuarios', 'otros', 'Vestuarios y duchas (incluido)', 'fijo', 0, null,
   'Vestuarios y duchas para el evento.', 98),
  ('otro', 'otros', 'Otro concepto', 'unidad', 0, null, '{descripcion}', 99)
on conflict (key) do nothing;

-- Plantilla de email para enviar el presupuesto (editable en Gestión > Plantillas).
insert into email_templates (key, name, subject, body) values (
  'presupuesto_evento',
  'Presupuesto de evento',
  'Presupuesto evento deportivo - {{empresa}}',
  E'Hola {{nombre}},\n\nTe adjuntamos el presupuesto del evento deportivo para {{empresa}} ({{fecha}}).\n\nTotal: {{total}}\n\nCualquier duda o cambio que necesitéis, estamos a vuestra disposición.\n\nUn saludo,\n{{club}}'
) on conflict (key) do nothing;

-- Los tres últimos presupuestos enviados (PDF de GRUPPE, Power Electronics y
-- CECOTEC), para tener historial desde el primer día y poder duplicarlos.
insert into event_quotes (club_id, title, company, event_date, date_label, participants, lines, services, services_custom, prizes_text, total, status, sent_at)
select c.id, q.title, q.company, q.event_date, q.date_label, q.participants, q.lines::jsonb, q.services::jsonb, true, q.prizes_text, q.total, 'enviado', now()
from (select id from clubs order by created_at limit 1) c
cross join (values
  ('EVENTO DEPORTIVO', 'GC-GRUPPE', date '2026-11-21', 'Sábado 21 noviembre 2026', 60,
   '[{"id":"l1","key":"pista_padel_indoor","label":"Pista de pádel indoor","unit":"pista_hora","qty":13,"hours":6,"price":20,"horario":"de 9:00 a 15:00"},
     {"id":"l2","key":"botes_bolas","label":"Botes de bolas","unit":"unidad","qty":15,"hours":1,"price":7},
     {"id":"l3","key":"gestion_integral","label":"Gestión integral del torneo","unit":"fijo","qty":1,"hours":1,"price":300}]',
   '["Organización de un torneo de pádel para 20/30 parejas.","Reserva de pista indoor para el desarrollo del evento.","Horario de 9:00 a 15:00","Bolas premium para el evento","TV con publicidad, roll ups, ... durante el desarrollo del evento.","Mesa de control (mesas y sillas) para la gestión del evento","Gestión deportiva del evento dirigido por juez arbitro","Gestión de cuadros y enfrentamientos","Personal de apoyo en recepción durante el evento.","Servicio de taquillas","Vestuarios y duchas para el evento."]',
   null, 1965),
  ('EVENTO DEPORTIVO POWER ELECTRONICS', 'Power Electronics', date '2026-11-07', 'Sábado 7 noviembre 2026', 152,
   '[{"id":"l1","key":"pista_padel_indoor","label":"Pista de pádel indoor","unit":"pista_hora","qty":22,"hours":5,"price":23,"horario":"de 9:30 a 14:30"},
     {"id":"l2","key":"cupon_premio","label":"Cupón regalo (premio)","unit":"unidad","qty":8,"hours":1,"price":80,"descripcion":"8 cupones de 80€ para la web: https://www.padelnuestro.com/"},
     {"id":"l3","key":"gestion_integral","label":"Gestión integral del torneo","unit":"fijo","qty":1,"hours":1,"price":400},
     {"id":"l4","key":"botes_bolas","label":"Botes de bolas","unit":"unidad","qty":23,"hours":1,"price":7}]',
   '["Organización de un torneo de pádel para 152 jugadores.","Reserva de todas las pistas indoor + 2/3 pistas outdoor de cortesía para calentar o juego libre.","Horario de 9:30 a 14:30","Bolas premium para el evento","TV con publicidad, roll ups, ...","Mesa de control (mesas y sillas) para la gestión del evento","Gestión deportiva del evento dirigido por juez arbitro","Gestión de cuadros y enfrentamientos","Personal de apoyo en recepción durante el evento.","Servicio de taquillas","Vestuarios y duchas para el evento."]',
   '8 cupones de 80€ para la web: https://www.padelnuestro.com/', 3731),
  ('EVENTO DEPORTIVO CECOTEC', 'CECOTEC', date '2026-10-02', 'Viernes 2 octubre 2026', 22,
   '[{"id":"l1","key":"pista_padel_indoor","label":"Pista de pádel indoor","unit":"pista_hora","qty":6,"hours":3,"price":23,"horario":"de 17:00 a 20:00"},
     {"id":"l2","key":"campo_futbol7","label":"Campo de fútbol 7","unit":"pista_hora","qty":1,"hours":3,"price":90,"horario":"de 17:00 a 20:00"}]',
   '["Reserva de 6 pistas de pádel indoor para el desarrollo del evento.","Reserva de 1 campo de fútbol 7 para el desarrollo del evento.","Horario del evento deportivo: de 17:00 a 20:00","Vestuarios y duchas para el evento"]',
   null, 684)
) as q(title, company, event_date, date_label, participants, lines, services, prizes_text, total)
where not exists (select 1 from event_quotes e where e.company = q.company and e.event_date = q.event_date);
